config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PhotoMap
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_header.html.haml
.header
  %h1.header__text
    = link_to 'PHOTO MAP', posts_path

app/views/posts/index.html.haml
= render 'header'

.content
  %h1.content__top
    日本の美しい写真を撮れる場所を共有しよう！！
  %p.content__text
    = link_to '投稿ページにいく', new_post_path
  %p.content__text
    = link_to '写真を見にいく'

app/views/posts/new.html.haml
= render 'header'

.main-content
  %h1.main-content__text
    新規投稿の作成
  .main-content__form
    = form_with model: @post do |form|
      = form.text_field :name, placeholder: "タイトル"
      = form.text_area :text, placeholder: "コメント" , rows: "10"
      = form.submit "SEND"
  .main-content__btn
    投稿する